version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: meal_planner
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    command: --init-file /docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db_data:

